- name: install nginx
  yum: name=nginx state=present
  tags: nginx

- name: service nginx
  service: name=nginx state=started enabled=yes
  tags: nginx

- name: nginx template copy
  template: >
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
    backup=yes
  notify: restart nginx
  tags: nginx

- name: edit log-dir
  file: path=/var/log/nginx/ mode=0755
  tags: nginx